#!/bin/bash

# One-command deployment guide for MFE PCF Solution
# This file provides quick CLI commands for deployment

echo "=================================================="
echo "MFE PCF Solution - Deployment Commands"
echo "=================================================="
echo ""

echo "📦 BUILD STATUS:"
echo "  ✓ mfe-transformation: 568K (ready)"
echo "  ✓ mfe-compliance: 564K (ready)"
echo "  ✓ api: 4.7M (ready)"
echo ""

echo "=== OPTION 1: NETLIFY CLI DEPLOYMENT ==="
echo ""
echo "# Install Netlify CLI (one-time)"
echo "npm install -g netlify-cli"
echo ""
echo "# Login to Netlify"
echo "netlify login"
echo ""
echo "# Deploy MFE 1 (Transformation)"
echo "netlify deploy --prod --dir apps/mfe-transformation/dist --site mfe-transformation"
echo ""
echo "# Deploy MFE 2 (Compliance)"
echo "netlify deploy --prod --dir apps/mfe-compliance/dist --site mfe-compliance"
echo ""

echo "=== OPTION 2: NETLIFY DROP (No CLI Needed) ==="
echo ""
echo "1. Visit: https://app.netlify.com/drop"
echo "2. Drag & drop folders:"
echo "   • apps/mfe-transformation/dist"
echo "   • apps/mfe-compliance/dist"
echo "3. Get instant HTTPS URLs"
echo ""

echo "=== OPTION 3: GIT-BASED NETLIFY DEPLOYMENT ==="
echo ""
echo "# Setup (one-time)"
echo "git init"
echo "git add ."
echo "git commit -m 'Initial commit'"
echo "git remote add origin https://github.com/YOUR-USERNAME/mfe-pcf.git"
echo "git push -u origin main"
echo ""
echo "# Then in Netlify UI:"
echo "# 1. Go to app.netlify.com"
echo "# 2. Click 'Add new site' → 'Import existing project'"
echo "# 3. Connect GitHub"
echo "# 4. For each site, configure:"
echo "#    Build command: cd apps/mfe-[name] && npm run build"
echo "#    Publish dir: apps/mfe-[name]/dist"
echo ""

echo "=== API SERVER DEPLOYMENT TO RENDER ==="
echo ""
echo "1. Go to: https://render.com"
echo "2. Click: New → Web Service"
echo "3. Connect your GitHub repo"
echo "4. Configure:"
echo ""
echo "   Name: mfe-auth-api"
echo "   Environment: Node"
echo "   Build Command: cd apps/api && npm install"
echo "   Start Command: cd apps/api && npm start"
echo "   Port: 3000"
echo ""
echo "5. Environment Variables:"
echo "   JWT_SECRET = (your-secret-key)"
echo "   NODE_ENV = production"
echo ""
echo "6. Click Deploy!"
echo ""

echo "=== API SERVER DEPLOYMENT TO RAILWAY ==="
echo ""
echo "1. Go to: https://railway.app"
echo "2. New Project → From GitHub repo"
echo "3. Select this repository"
echo "4. Add SERVICE from Dockerfile or Procfile:"
echo ""
echo "   [Procfile]"
echo "   web: cd apps/api && npm start"
echo ""
echo "5. Add environment variables in dashboard"
echo "6. Deploy!"
echo ""

echo "=== VERIFICATION AFTER DEPLOYMENT ==="
echo ""
echo "# Test API Health"
echo "curl https://your-api.onrender.com/api/health"
echo ""
echo "# Test Login"
echo "curl -X POST https://your-api.onrender.com/api/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"email\":\"demo@contoso.com\",\"password\":\"Pass@123\"}'"
echo ""
echo "# Verify CORS from MFE (check browser console)"
echo "fetch('https://your-api.onrender.com/api/login', {"
echo "  method: 'POST',"
echo "  headers: {'Content-Type': 'application/json'},"
echo "  body: JSON.stringify({email: 'demo@contoso.com', password: 'Pass@123'})"
echo "}).then(r => r.json()).then(console.log)"
echo ""

echo "=================================================="
echo "✓ All applications are built and ready!"
echo "=================================================="
